ApnSetting apn = new ApnSetting.Builder()
    .setApnTypeBitmask(
        ApnSetting.TYPE_DEFAULT | ApnSetting.TYPE_MMS | ApnSetting.TYPE_SUPL // интернет + MMS + A-GPS
    )
    .setApnName("h2g2") // Основной Google Fi APN
    .setEntryName("Google Fi")
    .setMmsc(Uri.parse("http://m.fi.goog/mms/wapenc")) // Центр отправки/приёма MMS
    // Следующие поля НЕ заполняются, так как у Google Fi нет MMS Proxy и Port:
    //.setMmsProxyAddress((String)null)
    //.setMmsProxyPort(0) // или можно просто не указывать эти параметры вовсе!
    // Для Google Fi username и password НЕ требуются
    // .setUser(null)
    // .setPassword(null)
